Copyright (c) Microsoft Corporation. All rights reserved.

Licensed under the MIT License.

# Lab 3: Automated Machine Learning with AutomML
_**Classification with Local Compute**_

## Introduction
In this lab, you will use your AdeventureWorks model training feature data you created earlier, to let AutoML find the best performing model.

In this notebook you will learn how to:
1. Create an `Experiment` in an existing `Workspace`.
2. Configure AutoML using `AutoMLConfig`.
3. Train the model using local compute.
4. Explore the results.
5. Test the best fitted model.

## Setup

As part of the setup you have already created an Azure ML `Workspace` object. For AutoML you will need to create an `Experiment` object, which is a named object in a `Workspace` used to run experiments.

In [1]:
import azureml.core
print(azureml.core.VERSION)

1.0.72


In [2]:
from azureml.core import Workspace

# check core SDK version number
print("Azure ML SDK Version: ", azureml.core.VERSION)

Azure ML SDK Version:  1.0.72


## Connect to your Azure Machine Learning service workspace.

There are two ways to do this:

- Using the workspace config file we created earlier.
- Calling the workspace get() method 

In [3]:
# Method 1: Using the workspace config file...

ws = Workspace.from_config()
print(ws.name, ws.location, ws.resource_group, ws.location, sep='\t')

MBAUER	eastus	RG-DP100	eastus


In [4]:
# Method 2: Using the get() method...

from azureml.core import Workspace, Experiment, Run
ws = Workspace.get(name='MBAUER',
                   subscription_id='52b56929-ee84-495c-91c3-a84dfacbc9d2',
                   resource_group='RG-DP100'
                  )
print(ws.name, ws.location, ws.resource_group, ws.location, sep='\t')

MBAUER	eastus	RG-DP100	eastus


In [5]:
import logging

from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

import azureml.core
from azureml.core.experiment import Experiment
from azureml.core.workspace import Workspace
from azureml.train.automl import AutoMLConfig
print('Modules loaded...')

Modules loaded...


In [6]:
#ws = Workspace.from_config()

# Choose a name for the experiment and specify the project folder.
experiment_name = 'dp100lab-automl'
project_folder = './dp100lab'

experiment = Experiment(ws, experiment_name)

output = {}
output['SDK version'] = azureml.core.VERSION
output['Subscription ID'] = ws.subscription_id
output['Workspace Name'] = ws.name
output['Resource Group'] = ws.resource_group
output['Location'] = ws.location
output['Project Directory'] = project_folder
output['Experiment Name'] = experiment.name
pd.set_option('display.max_colwidth', -1)
outputDf = pd.DataFrame(data = output, index = [''])
outputDf.T

SDK version        1.0.72                              
Subscription ID    52b56929-ee84-495c-91c3-a84dfacbc9d2
Workspace Name     MBAUER                              
Resource Group     RG-DP100                            
Location           eastus                              
Project Directory  ./dp100lab                          
Experiment Name    dp100lab-automl

## Connect to existing workspace.

# Explore data
### You already explored the data in the last lab. You need to copy the data into the cloud so it can be accessed by your cloud training environment. We saved the model training data to a csv file so all we have to do is load it.

In [8]:
import pandas as pd

df_features = pd.read_csv(r'./BikeModelFeatures.csv')
df_features.head()

Unnamed: 0  BikeTypeCat  AgeBandCat  IncomeBandCat  MaritalStatusCat  \
0  0           1            5           1              1                  
1  1           0            3           0              1                  
2  2           0            5           0              1                  
3  3           1            5           1              0                  
4  4           0            3           1              1                  

   OccupationCat  CommuteDistanceCat  GenderCat  ChildrenAtHomeCat  \
0  1              2                   1          0                   
1  2              0                   0          1                   
2  3              2                   0          0                   
3  1              1                   1          0                   
4  3              4                   0          0                   

   CountryRegionCodeCat  HouseOwnerFlagCat  EducationCat  
0  1                     1                  0             
1  3                     0                  2             
2  5                     1                  2             
3  5                     1                  1             
4  0                     0                  0

In [9]:
from sklearn.model_selection import train_test_split

x_train , x_test = train_test_split(df_features.values,test_size=0.2)       #test_size=0.5(whole_data)

In [10]:
y_train = x_train[:,3]
y_train

array([0, 1, 0, ..., 0, 0, 0])

In [11]:
y_test = x_test[:,3]
y_test

array([0, 1, 1, ..., 0, 1, 0])

In [12]:
x_train = x_train[:,0:3]
x_train

array([[ 6656,     0,     4],
       [10288,     1,     2],
       [ 5305,     1,     3],
       ...,
       [  846,     0,     2],
       [ 3494,     1,     4],
       [10303,     0,     3]])

In [13]:
x_test = x_test[:,0:3]
x_test

array([[14132,     2,     2],
       [ 2535,     1,     3],
       [  832,     1,     3],
       ...,
       [ 6681,     0,     2],
       [11146,     0,     2],
       [ 4423,     1,     3]])

In [14]:
print(len(x_train))
len(x_test)

12164


3041

## Train

Instantiate an `AutoMLConfig` object to specify the settings and data used to run the experiment.

|Property|Description|
|-|-|
|**task**|classification or regression|
|**primary_metric**|This is the metric that you want to optimize. Regression supports the following primary metrics: <br><i>spearman_correlation</i><br><i>normalized_root_mean_squared_error</i><br><i>r2_score</i><br><i>normalized_mean_absolute_error</i>|
|**iteration_timeout_minutes**|Time limit in minutes for each iteration.|
|**iterations**|Number of iterations. In each iteration AutoML trains a specific pipeline with the data.|
|**n_cross_validations**|Number of cross validation splits.|
|**X**|(sparse) array-like, shape = [n_samples, n_features]|
|**y**|(sparse) array-like, shape = [n_samples, ], targets values.|
|**path**|Relative path to the project folder. AutoML stores configuration files for the experiment under this folder. You can specify a new empty folder.|

In [15]:
automl_config = AutoMLConfig(task = 'classification',
                             iteration_timeout_minutes = 10,
                             iterations = 10,
                             primary_metric = 'precision_score_weighted',
                             n_cross_validations = 5,
                             debug_log = 'automl.log',
                             verbosity = logging.INFO,
                             X = x_train, 
                             y = y_train,
                             preprocess=True,
                             path = project_folder)

WARNING - The AutoMLConfig inputs you have specified will soon be deprecated. Please use the AutoMLConfig shown in our documentation: https://aka.ms/AutoMLConfig


In [16]:
print('Done')

Done


Call the `submit` method on the experiment object and pass the run configuration. Execution of local runs is synchronous. Depending on the data and the number of iterations this can run for a while.
In this example, we specify `show_output = True` to print currently running iterations to the console.

In [ ]:
local_run = experiment.submit(automl_config, show_output = True)

Running on local machine
Parent Run ID: AutoML_1b77ed25-b8c0-48ff-af6b-b184f7fa8ef6
Current status: DatasetFeaturization. Beginning to featurize the dataset.
Current status: DatasetEvaluation. Gathering dataset statistics.
Current status: FeaturesGeneration. Generating features for the dataset.
Current status: DatasetFeaturizationCompleted. Completed featurizing the dataset.
Current status: DatasetCrossValidationSplit. Generating individually featurized CV splits.

****************************************************************************************************
DATA GUARDRAILS SUMMARY:
For more details, use API: run.get_guardrails()

TYPE:         Class Balancing Detection
STATUS:       ALERTED
DESCRIPTION:  Classes in the training data are imbalanced.

TYPE:         Missing Values Imputation
STATUS:       PASSED
DESCRIPTION:  There were no missing values found in the training data.

TYPE:         High Cardinality Feature Detection
STATUS:       PASSED
DESCRIPTION:  Your inputs were

In [63]:
local_run

Run(Experiment: automl-local-classification,
Id: AutoML_2e1a8864-811d-45cf-adf6-4a161a165ef6,
Type: automl,
Status: Completed)

## Results

#### Widget for Monitoring Runs

The widget will first report a "loading" status while running the first iteration. After completing the first iteration, an auto-updating graph and table will be shown. The widget will refresh once per minute, so you should see the graph update as child runs complete.

**Note:** The widget displays a link at the bottom. Use this link to open a web interface to explore the individual run details.

In [ ]:
from azureml.widgets import RunDetails
RunDetails(local_run).show() 


#### Retrieve All Child Runs
You can also use SDK methods to fetch all the child runs and see individual metrics that we log.

In [ ]:
children = list(local_run.get_children())
metricslist = {}
for run in children:
    properties = run.get_properties()
    metrics = {k: v for k, v in run.get_metrics().items() if isinstance(v, float)}
    metricslist[int(properties['iteration'])] = metrics

rundata = pd.DataFrame(metricslist).sort_index(1)
rundata

### Retrieve the Best Model

Below we select the best pipeline from our iterations. The `get_output` method returns the best run and the fitted model. The Model includes the pipeline and any pre-processing.  Overloads on `get_output` allow you to retrieve the best run and fitted model for *any* logged metric or for a particular *iteration*.

In [ ]:
best_run, fitted_model = local_run.get_output()
print(best_run)
print(fitted_model)

#### Best Model Based on Any Other Metric
Show the run and the model that has the smallest `root_mean_squared_error` value (which turned out to be the same as the one with largest `spearman_correlation` value):

In [18]:
lookup_metric = "f1_score_macro"
best_run, fitted_model = local_run.get_output(metric = lookup_metric)
print(best_run)
print(fitted_model)

Run(Experiment: automl-local-regression,
Id: AutoML_64ef6e81-abdf-47b5-a4a6-acb0cd127f66_8,
Type: None,
Status: Completed)
Pipeline(memory=None,
     steps=[('StandardScalerWrapper', <automl.client.core.common.model_wrappers.StandardScalerWrapper object at 0x7fbd8fef6160>), ('LassoLars', LassoLars(alpha=0.001, copy_X=True, eps=2.220446049250313e-16,
     fit_intercept=True, fit_path=True, max_iter=500, normalize=False,
     positive=False, precompute='auto', verbose=False))])


#### Model from a Specific Iteration
Show the run and the model from the third iteration:

In [19]:
iteration = 3
third_run, third_model = local_run.get_output(iteration = iteration)
print(third_run)
print(third_model)

Run(Experiment: automl-local-regression,
Id: AutoML_64ef6e81-abdf-47b5-a4a6-acb0cd127f66_3,
Type: None,
Status: Completed)
Pipeline(memory=None,
     steps=[('StandardScalerWrapper', <automl.client.core.common.model_wrappers.StandardScalerWrapper object at 0x7fbd8fe8e0b8>), ('LightGBMRegressor', <automl.client.core.common.model_wrappers.LightGBMRegressor object at 0x7fbd8fecd160>)])


## Test

Predict on training and test set, and calculate model accuracy.

In [ ]:
y_predtest = fitted_model.predict(x_test)

In [ ]:
# calculate accuracy on the prediction
acc = np.average(y_predtest == y_test)
print('Accuracy is', acc)